project:
  type: website
  output-dir: docs

website:
  title: "The Triple E Project"
  favicon: teh4l.webp
  site-url: https://amxlia.github.io/tripleE
  repo-url: https://github.com/amxlia/tripleE
  navbar: false
  sidebar: 
    logo: teh4l.webp
    search: false 
    style: "docked"
    contents: 
      - text: "Information"
        href: "index.qmd"
      - href: "descriptives.qmd"
      
      #- section: "MOST Full Factorial Analysis"
       # href: MOST.qmd
       # contents:
         # - MOST_baseline_balance.qmd
         # - MOST_ancova.qmd
         # - MOST_assumptions.qmd
         # - MOST_predicted_outcomes.qmd
 

format:
  html:
    embed-resources: true
    grid:
      sidebar-width: 270px
    code-fold: true
    code-summary: "Show/hide the code"
    code-overflow: wrap
    code-link: true
    code-copy: true
    syntax-highlighting: 
      light: arrow
      dark: arrow
    theme: 
      light: 
        - flatly
        - styles.scss
    toc: true
    toc-location: right
    fig-title: "Figure"
    cap-location: top
    crossref:
      fig-title: "Figure"
      tbl-title: "Table"

knitr:
  opts_chunk:
    ft.htmlscroll: false
    message: false
    warning: false

execute:
  #echo: false
  warning: false
  message: false
  cache: true         
  freeze: auto

