---
title: "The Triple E Project"
author: "Amelia Henry"
date: today
toc: false
---
This project contains the analysis for the Triple E trial. 

The published protocol can be viewed [here @ BMC Public Health](https://link.springer.com/article/10.1186/s12889-024-20124-5) 

The trial is registered at the Australian New Zealand Clinical Trials Registry ([ACTRN12623000399695](https://anzctr.org.au/Trial/Registration/TrialReview.aspx?id=385520&isReview=true)). Date registered: 19/04/2023. 

## Background 
Digital, or eHealth, interventions are highly promising approaches to help adolescents improve their health behaviours and reduce their risk of chronic disease. However, they often have low uptake and retention. There is also a paucity of high-quality research into the predictors of eHealth engagement, and a lack of studies that have systematically evaluated existing engagement strategies in adolescent populations. This randomised controlled trial primarily aims to assess the effectiveness of different strategies in increasing engagement with a healthy lifestyles app, Health4Life. Associations between the engagement strategies and improvements in adolescent health behaviours (healthy eating, physical activity, sleep, recreational screen time, smoking, alcohol use) will also be examined, along with potential predictors of adolescents’ intentions to use health apps and their use of the Health4Life app.

## Methods
The trial uses a 2x2x2x2 full factorial design, with four engagement strategies (gamification, health coaching, parent resources, and text messages) as the factors. All participants received access to the Health4Life app. Participants were randomly allocated to one of 16 conditions (different combinations of the four engagement. strategies to be evaluated). Adolescents and parents/guardians completed baseline assessments and a follow-up assessment after 3 months. The primary outcome, app engagement, is assessed via an app Engagement Index (EI) using data collected from the back-end of the Health4Life app, as well as the Mobile App Rating Scale - User Version (UMars), which is measured during the follow-up survey. 

